
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leesly Falcon
 * Es nuestro menú para poder llamar a las diferentes ventanas.
 */
public class Menu extends javax.swing.JFrame {
  private Login Login;
  
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        est = new javax.swing.JPanel();
        btnpilas2 = new javax.swing.JButton();
        btnpilas1 = new javax.swing.JButton();
        btnpilasdefi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btncolas2 = new javax.swing.JButton();
        btncolas1 = new javax.swing.JButton();
        btncolasdefi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnlistas2 = new javax.swing.JButton();
        btnlistas1 = new javax.swing.JButton();
        btnlistasdefi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        login = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ordar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jLabel2.setText("jLabel2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estructuras Lineales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        est.setBackground(new java.awt.Color(153, 153, 255));
        est.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pilas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N

        btnpilas2.setBackground(new java.awt.Color(153, 153, 255));
        btnpilas2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnpilas2.setText("Ejemplo ");
        btnpilas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilas2ActionPerformed(evt);
            }
        });

        btnpilas1.setBackground(new java.awt.Color(153, 153, 255));
        btnpilas1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnpilas1.setText("Ejemplo ");
        btnpilas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilas1ActionPerformed(evt);
            }
        });

        btnpilasdefi.setBackground(new java.awt.Color(153, 153, 255));
        btnpilasdefi.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnpilasdefi.setText("Definición");
        btnpilasdefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilasdefiActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mi proyecto.png"))); // NOI18N

        javax.swing.GroupLayout estLayout = new javax.swing.GroupLayout(est);
        est.setLayout(estLayout);
        estLayout.setHorizontalGroup(
            estLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(estLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(estLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnpilasdefi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnpilas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnpilas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        estLayout.setVerticalGroup(
            estLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, estLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnpilasdefi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnpilas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnpilas2)
                .addGap(18, 18, 18))
        );

        jPanel2.add(est, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 140, 260));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Colas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N

        btncolas2.setBackground(new java.awt.Color(153, 204, 255));
        btncolas2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btncolas2.setText("Ejemplo ");
        btncolas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncolas2ActionPerformed(evt);
            }
        });

        btncolas1.setBackground(new java.awt.Color(153, 204, 255));
        btncolas1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btncolas1.setText("Ejemplo ");
        btncolas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncolas1ActionPerformed(evt);
            }
        });

        btncolasdefi.setBackground(new java.awt.Color(153, 204, 255));
        btncolasdefi.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btncolasdefi.setText("Definición");
        btncolasdefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncolasdefiActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triggered-anime (1).gif"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btncolasdefi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncolas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncolas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncolasdefi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncolas1)
                .addGap(12, 12, 12)
                .addComponent(btncolas2)
                .addGap(20, 20, 20))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 150, 260));

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N

        btnlistas2.setBackground(new java.awt.Color(153, 255, 255));
        btnlistas2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnlistas2.setText("Ejemplo ");
        btnlistas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistas2ActionPerformed(evt);
            }
        });

        btnlistas1.setBackground(new java.awt.Color(153, 255, 255));
        btnlistas1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnlistas1.setText("Ejemplo ");
        btnlistas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistas1ActionPerformed(evt);
            }
        });

        btnlistasdefi.setBackground(new java.awt.Color(153, 255, 255));
        btnlistasdefi.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnlistasdefi.setText("Definición");
        btnlistasdefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistasdefiActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/f1074fca0016e1db0500383e29a9233bfab58e6b_hq (5).gif"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnlistas1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlistas2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlistasdefi)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnlistasdefi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlistas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlistas2)
                .addGap(14, 14, 14))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 170, 260));

        jMenu1.setText("Estructuras");

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jMenu1.add(login);

        jMenuItem1.setText("Aplicación ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Unidad 5/6");

        ordar.setText("Ordenar");
        ordar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordarActionPerformed(evt);
            }
        });
        jMenu2.add(ordar);

        jMenuItem2.setText("Busqueda");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Arboles");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // mandamos a llamar a la ventana login
        Login = new Login();
        Login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void btncolas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolas2ActionPerformed
        //segundo ejemplo 
        ColaV2 ejemploC=new ColaV2();
        ejemploC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncolas2ActionPerformed

    private void btnlistas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistas2ActionPerformed
        // segundo ejemplo de listas 
        ListaBuscador objeto = new ListaBuscador();
       objeto.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnlistas2ActionPerformed

    private void btncolas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolas1ActionPerformed
        // primer ejemplo de colas
        Cola ejemploC=new Cola();
        ejemploC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncolas1ActionPerformed

    private void btnlistas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistas1ActionPerformed
        // primer ejemplo listas 
         Lista ejemploL=new Lista();
        ejemploL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlistas1ActionPerformed

    private void btnpilas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilas1ActionPerformed
        // Primer ejemplo de pilas 
         Pila ejercicio= new Pila();
        ejercicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpilas1ActionPerformed

    private void btnpilas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilas2ActionPerformed
        // segundo ejemplo de pilas 
        Pila2 ejercicio= new Pila2();
        ejercicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpilas2ActionPerformed

    private void btnpilasdefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilasdefiActionPerformed
        // concepto
         JOptionPane.showMessageDialog(null, "La pila es una secuencia de elementos del mismo tipo en la" +"\n "
                                                         + "que el acceso a la misma se realiza por un único lugar denominado"+"\n "+
                                                         "cima: Vemos como el acceso a los elementos de la pila se realiza siempre "+"\n "+
                                                    "sobre un único extremo. Las operaciones que caracterizan la pila son las de" +"\n "+
                                                    "introducir un nuevo elemento sobre la cima (push) y la de extraer el elemento "+"\n "+
                                                      "situado en la cima (pop).");
    }//GEN-LAST:event_btnpilasdefiActionPerformed

    private void btncolasdefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolasdefiActionPerformed
        // concepto
        JOptionPane.showMessageDialog(null, "caracterizada por ser una secuencia de elementos en la que"+"\n "+
                 "la operación de inserción push se realiza por un extremo y la operación de extracción pull por el otro."+"\n "
                + "También se le llama estructura FIFO, debido a que el primer elemento en entrar será también el primero en salir.");
    }//GEN-LAST:event_btncolasdefiActionPerformed

    private void btnlistasdefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistasdefiActionPerformed
        // concepto 
        JOptionPane.showMessageDialog(null, " representa una colección de elementos ordenados. puede contener elementos repetidos."+"\n "
                + " cada elemento de la lista tiene un índice que lo ubica dentro de la misma.");
    }//GEN-LAST:event_btnlistasdefiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        biblioteca objeto = new biblioteca();
        objeto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ordarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordarActionPerformed
        Burbuja ob = new Burbuja();  
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ordarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       BSecuencial ob = new BSecuencial();
       ob.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      Frame ob = new Frame();
      ob.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncolas1;
    private javax.swing.JButton btncolas2;
    private javax.swing.JButton btncolasdefi;
    private javax.swing.JButton btnlistas1;
    private javax.swing.JButton btnlistas2;
    private javax.swing.JButton btnlistasdefi;
    private javax.swing.JButton btnpilas1;
    private javax.swing.JButton btnpilas2;
    private javax.swing.JButton btnpilasdefi;
    private javax.swing.JPanel est;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuItem login;
    private javax.swing.JMenuItem ordar;
    // End of variables declaration//GEN-END:variables
}
